### ISSUE TITLE
NeurIPS 2023 Soptlight WITRAN

### ISSUE THREAD

**Issue by shenzekai** [ddz16/TSFpaper#11]
Hi， a new paper about long-term time series forecasting based on RNN which accepted by NeurIPS 2023 as Spotlight.
2023 [NeurIPS] WITRAN: Water-wave Information Transmission and Recurrent Acceleration Network for Long-range Time Series Forecasting
Paper:https://openreview.net/forum?id=y08bkEtNBK
Code:https://github.com/Water2sea/WITRAN

**Comment by ddz16** [comment]
Thank you for your reminder, I have added this paper.
