### ISSUE TITLE
A suggestion to add a pre-training method article

### ISSUE THREAD

**Issue by realwangjiahao** [ddz16/TSFpaper#12]
Thank you for summarizing these articles. It is very helpful to my study of time series.

    I am very interested in the Pretrain & Representation part, and your summary is also very comprehensive.
    I recently read an article about pre-training. The author proposes TimeMAE, a novel self-supervised paradigm for learning transferrable time series representations based on transformer networks. 
    Could you please read this article and add it to the Pretrain & Representation part？
    You can find this article at [https://arxiv.org/abs/2303.00320]

    With best regards.

**Comment by ddz16** [comment]
Thank you for your reminder, I have added this paper.
