### ISSUE TITLE
Add paper

### ISSUE THREAD

**Issue by wengwenchao123** [ddz16/TSFpaper#16]
[[Pattern Recognition] Decomposition Dynamic Graph Conolutional Recurrent Network for Traffic Forecasting
](https://doi.org/10.1016/j.patcog.2023.109670)
code:[https://github.com/wengwenchao123/DDGCRN]( https://github.com/wengwenchao123/DDGCRN)

[[Neural Networks] RGDAN: A random graph diffusion attention network for traffic prediction](https://doi.org/10.1016/j.neunet.2023.106093)

code: [https://github.com/wengwenchao123/RGDAN](https://github.com/wengwenchao123/RGDAN)

**Comment by ddz16** [comment]
Thank you for your reminder, I have added these papers.
