### ISSUE TITLE
[SageFormer] Add Code

### ISSUE THREAD

**Issue by kwan-0915** [ddz16/TSFpaper#17]
The author has open-sourced their code, here is the link : [SageFormer](https://github.com/zhangzw16/SageFormer)

IEEE: [SageFormer: Series-Aware Framework for Long-Term Multivariate Time-Series Forecasting](https://ieeexplore.ieee.org/abstract/document/10423755)

Arxiv: [SageFormer: Series-Aware Framework for Long-term Multivariate Time Series Forecasting](https://arxiv.org/abs/2307.01616)

**Comment by ddz16** [comment]
Thank you for your reminder, I have added this link.
