### ISSUE TITLE
Time series model fusion

### ISSUE THREAD

**Issue by Caelyn-gao** [ddz16/TSFpaper#28]
Hi author,

Thank you for this wonderful repo. The insights and resources you have made available have been incredibly useful for me.

I am wondering if it is possible to add a topic to collect the literature on time series model fusion!

Thank you! Have a good day!

**Comment by ddz16** [comment]
Can you provide me with the titles or links of a few papers in this topic? I'd like to read them first to determine if they are suitable to be included in this repo. Thank you.

**Comment by ddz16** [comment]
Due to no response for a long time, the issue will be closed.
