### ISSUE TITLE
Stock Price Prediction Using a Graph-Mamba Approach

### ISSUE THREAD

**Issue by Ali-Meh619** [ddz16/TSFpaper#37]
Hello @ddz16,

I and my colleagues recently submitted a paper with the title "Mamba Meets Financial Markets: A Graph-Mamba Approach for Stock Price Prediction". Here is the link to the arxiv version:
https://arxiv.org/abs/2410.03707

I would appreciate it if you can put that on your github account "TSFpaper".
Thank you in advance for your consideration.

All the best,
Ali Mehrabian

**Comment by ddz16** [comment]
Thank you for your reminder, I have added the paper.
