### ISSUE TITLE
Add a tag for whether the design supports global forecasting (or only local)

### ISSUE THREAD

**Issue by zacps** [ddz16/TSFpaper#5]
As title, it would be useful to categorise these models by if they support global forecasting (training on multiple time series and predicting on unseen series).

**Comment by ddz16** [comment]
Sorry for the late reply. Some models are specifically designed for this purpose, which is similar to the domain adaptation in time series. However, I believe that as long as the unseen series are similar to the series in the training set, almost all models can naturally achieve this. Therefore, I don't currently plan to classify models based on this. But thank you for your suggestion.
